# DO NOT EDIT THIS FILE
#
# To set up cross-compilation, create the file
# $(ROS_ROOT)/rostoolchain.cmake.  It gets read first, prior to 
# any of cmake's system tests.

#############################################################
#
# An example for using the gumstix arm-linux toolchain is below.
# Copy these lines to $(ROS_ROOT)/rostoolchain.cmake to try them out. 
#
set(GLSDK_ROOTFS /home/x0221391/cardimage_copy/rootfs)
set(UBUNTU_ARM_ROOTFS /home/x0221391/ubuntu_arm/rootfs)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabihf-gcc-4.6)
set(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabihf-g++-4.6)
set(PYTHON_EXECUTABLE /usr/bin/python)
set(CMAKE_FIND_ROOT_PATH /usr/arm-linux-gnueabihf) 
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY) 
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)



#############################################################
# Cross-compilation loader
#
# This file is passed to cmake on the command line via
# -DCMAKE_TOOLCHAIN_FILE.

#############################################################
# look for user's toolchain file in $ROS_ROOT/rostoolchain.cmake
# find_file(TOOLCHAINCONFIG rostoolchain.cmake PATHS ENV ROS_ROOT NO_DEFAULT_PATH)
#if(TOOLCHAINCONFIG)
# include(${TOOLCHAINCONFIG})
#endif(TOOLCHAINCONFIG)
#############################################################

